<?php

#feneko.module

function feneko_code_permission() {
  return array(
    'see the catalog' => array(
      'title' => t('see the catalog'),
      'description' => t('see the catalog'),
    ),
  );
}

function feneko_code_menu(){
    $items['user/%user/logout'] = array(
        'title' => 'Log out',
      'page callback' => 'feneko_user_logout',
      'page arguments' => array('user_profile_form', 1),
      'access callback' => 'user_edit_access',
      'access arguments' => array(1),
      'type' => MENU_LOCAL_TASK,
    );

    $items['catalog/%/%'] = array(
        'title' => 'Feneko catalog',
      'page callback' => 'feneko_catalog',
      'page arguments' => array(1,2,3),
      'access callback' => 'user_access',
      'access arguments' => array('see the catalog'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'feneko_code.catalog.inc',
    );

    $items['admin/config/feneko'] = array(
      'title' => 'Feneko settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('feneko_flipper_settings'),
      'access callback' => 'user_access',
      'access arguments' => array('administer content'),
      'type' => MENU_LOCAL_TASK,
    );

  return $items;
}


/**
 * Implements hook_block_info().
 */
function feneko_code_block_info() {

  $blocks['feneko_code_flipper'] = array(
    'info' => t('link to flipper block'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function feneko_code_block_view($delta) {
  switch ($delta) {
    case 'feneko_code_flipper':
    return feneko_code_flipper();

  }
}

/**
 * Render block().
 */
function feneko_code_flipper(){
  global $language;
  $block = array();
  $block['subject'] = 'Catalogus';
  $block['content'] = '<div class="catalogus-links">'.l(t('Colors catalogus'),'catalog/colors/pdf',array(
    'attributes' => array(
      'class' => array('rodeknop'),
      'target'=>'_blank',
    )
    )).'</div><div class="catalogus-links">'.l(t('Screens catalogus'),'catalog/screens/pdf',array(
    'attributes' => array(
      'class' => array('rodeknop'),
      'target'=>'_blank',
    )
    )).'</div>';
  return $block;
}



function feneko_user_logout(){
  global $user;
  module_invoke_all('user_logout', $user);
  session_destroy();
  drupal_set_message(t('You are logged out'));
  drupal_goto('<front>');
}


function feneko_code_preprocess_node(&$vars){
  if($vars['type'] == 'offerte_xml_data' && $vars['view_mode']=='full') {
    $node = &$vars['node'];
    $file = $node->field_data_file['und'][0];
    $path = file_create_url($file['uri']);
    drupal_goto($path);
  }
}

function feneko_code_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'user_register_form') {
    $form['#submit'][]  = 'feneko_code_inform_admin';
  }
}

function feneko_code_inform_admin($form, &$form_state) {
  $values = $form_state['values'];
  $body = 'A user registered on feneko.be.
  Please check his/her account and activate it.
  His language is  ' . $values['language'] . '
  The user name is ' . $values['name'] . '
  The BTW nummer is ' . $values['field_btw_nummer']['und'][0]['value'] . '
  The Company is ' . $values['field_bedrijf']['und'][0]['value'] . '
  The telefoon is ' . $values['field_telefoon']['und'][0]['value'] . '
  Administrate the users here: http://feneko.be/admin/people .
  ';
  $to = 'jeremie@fenekobvba.be';
  $from = 'no-reply@feneko.be';
  $header_cc = 'david@fenekobvba.be';
  $header_cc = 'wouters.f@gmail.com';
  $subject = 'User registratie op [feneko.be]';
  $message = drupal_mail(
    'feneko_code',
    'user_registers',
    $to,
    user_preferred_language($user),
    array(
      'body' => $body,
      'subject' => $subject,
      'headers' => array(
        'Cc' => $header_cc,
        'Bcc' => $header_bcc,
      ),
      $from,
      TRUE)
    );
}


function feneko_code_mail($key, &$message, $params){
  if (isset($params['subject'])) {
    $message['subject'] = $params['subject'];
  }
  if (isset($params['body'])) {
    $message['body'][] = $params['body'];
  }
  if (isset($params['headers']) && is_array($params['headers'])) {
    $message['headers'] += $params['headers'];
  }
  switch ($key) {
    case 'user_registers':
      // do something specific for mails of type key1
      break;
   case 'key2':
      // do something specific for mails of type key2
      break;
   }

}


/**
 * Administrative forms and related.
 */
function feneko_flipper_settings() {
  $form = array();

  $form['screens'] = array(
    '#type' => 'fieldset',
    '#title' => t('Screens'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['colors'] = array(
    '#type' => 'fieldset',
    '#title' => t('Screens'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['colors']['feneko_catalogus_flipper_colors_nl'] = array(
    '#title' => t('Link to NL flipper COLORS'),
    '#type' => 'textfield',
    '#default_value' => variable_get('feneko_catalogus_flipper_colors_nl', ''),
  );
  $form['colors']['feneko_catalogus_flipper_colors_fr'] = array(
    '#title' => t('Link to FR flipper COLORS'),
    '#type' => 'textfield',
    '#default_value' => variable_get('feneko_catalogus_flipper_colors_fr', ''),
  );

  $form['screens']['feneko_catalogus_flipper_screens_nl'] = array(
    '#title' => t('Link to NL flipper SCREENS'),
    '#type' => 'textfield',
    '#default_value' => variable_get('feneko_catalogus_flipper_screens_nl', ''),
  );
 $form['screens']['feneko_catalogus_flipper_screens_fr'] = array(
    '#title' => t('Link to FR flipper SCREENS'),
    '#type' => 'textfield',
    '#default_value' => variable_get('feneko_catalogus_flipper_screens_fr', ''),
  );

  return system_settings_form($form);
}
